// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgNnluZv6v558dxYCdThJo28zwFWxfAKc',
    appId: '1:74971808115:web:af39a41e3633f8c6728506',
    messagingSenderId: '74971808115',
    projectId: 'deliveries-8f4de',
    authDomain: 'deliveries-8f4de.firebaseapp.com',
    storageBucket: 'deliveries-8f4de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqmcuavpxArPviKdCczb7rLHvirXh5t0Y',
    appId: '1:74971808115:android:0bbeaf7b453d227d728506',
    messagingSenderId: '74971808115',
    projectId: 'deliveries-8f4de',
    storageBucket: 'deliveries-8f4de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo2gD6IFpIT7ERfBzMMrPiNz2KVozNBlI',
    appId: '1:74971808115:ios:a0d82ea715cabadb728506',
    messagingSenderId: '74971808115',
    projectId: 'deliveries-8f4de',
    storageBucket: 'deliveries-8f4de.appspot.com',
    iosBundleId: 'com.example.deliveries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo2gD6IFpIT7ERfBzMMrPiNz2KVozNBlI',
    appId: '1:74971808115:ios:a0d82ea715cabadb728506',
    messagingSenderId: '74971808115',
    projectId: 'deliveries-8f4de',
    storageBucket: 'deliveries-8f4de.appspot.com',
    iosBundleId: 'com.example.deliveries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgNnluZv6v558dxYCdThJo28zwFWxfAKc',
    appId: '1:74971808115:web:aaeb141e75cde71f728506',
    messagingSenderId: '74971808115',
    projectId: 'deliveries-8f4de',
    authDomain: 'deliveries-8f4de.firebaseapp.com',
    storageBucket: 'deliveries-8f4de.appspot.com',
  );
}
